# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='team',
            field=models.CharField(default='', max_length=75),
        ),
    ]
